// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrement() {
  return window['go']['main']['App']['Decrement']();
}

export function GetCount() {
  return window['go']['main']['App']['GetCount']();
}

export function Increment() {
  return window['go']['main']['App']['Increment']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
